CREATE DATABASE FODS;
\c fods

CREATE DOMAIN RATING AS NUMERIC(3, 1) CHECK (VALUE BETWEEN 1.0 AND 5.0);

CREATE TABLE USERS (
    Uname VARCHAR(20) PRIMARY KEY,
    Pass VARCHAR NOT NULL,
    FirstName VARCHAR(30) NOT NULL,
    LastName VARCHAR(30),
    Phone NUMERIC(10) NOT NULL,
    Email VARCHAR(75) NOT NULL
);

CREATE TABLE CUSTOMERS (
    Cust_Uname VARCHAR(20) PRIMARY KEY,
    ALine1 VARCHAR(100) NOT NULL,
    ALine2 VARCHAR(100) NOT NULL,
    City VARCHAR(50) NOT NULL,
    Pin NUMERIC(6) NOT NULL
);

CREATE TABLE RESTAURANTS (
	Rest_Uname VARCHAR(20) NOT NULL,
	FSSAI NUMERIC(14) PRIMARY KEY,
	Rest_Name VARCHAR(50) NOT NULL,
	Img_Link VARCHAR,
	ALine1 VARCHAR(100) NOT NULL,
	ALine2 VARCHAR(100) NOT NULL,
	City VARCHAR(50) NOT NULL,
	Pin NUMERIC(6) NOT NULL,
	Lat NUMERIC(12,7) NOT NULL,
	Long NUMERIC(12,7) NOT NULL,
	IsOpen BOOLEAN NOT NULL,
	Rating RATING
);

CREATE TABLE RESTAURANT_PHONE (
	FSSAI NUMERIC(14) NOT NULL,
	Phone NUMERIC(10) PRIMARY KEY
);

CREATE TABLE DELIVERY_PERSONS (
	Del_Uname VARCHAR(20) PRIMARY KEY,
	VNo VARCHAR(20) NOT NULL,
	VModel VARCHAR(30) NOT NULL,
	VColour VARCHAR(15) NOT NULL
);

CREATE TABLE FOOD_ITEMS (
	ItemNo NUMERIC NOT NULL,
	FSSAI NUMERIC(14) NOT NULL,
	ItemName VARCHAR(32) NOT NULL,
	Img_Link VARCHAR,
	ItemDesc VARCHAR(1024),
	IsAvail BOOLEAN NOT NULL,
	IsVeg BOOLEAN NOT NULL,
	Cuisine VARCHAR(20),
	Mealtype VARCHAR(20) NOT NULL,
	Price NUMERIC(7,2) NOT NULL,
    PRIMARY KEY (ItemNo, FSSAI)
);

CREATE TABLE ORDERS (
	OrderNo SERIAL PRIMARY KEY,
	OrderTime TIMESTAMP NOT NULL,
    IsPlaced BOOLEAN NOT NULL,
	IsAssigned BOOLEAN NOT NULL,
	IsPrepared BOOLEAN NOT NULL,
	IsReceived BOOLEAN NOT NULL,
	IsDelivered BOOLEAN NOT NULL,
	IsPaid BOOLEAN NOT NULL,
	Cust_Uname VARCHAR(20) NOT NULL,
	FSSAI NUMERIC(14) NOT NULL,
	Del_Uname VARCHAR(20) NOT NULL
);

CREATE TABLE ORDER_CONTENT (
	OrderNo INTEGER NOT NULL,
	ItemNo NUMERIC NOT NULL,
	FSSAI NUMERIC(14) NOT NULL,
	Quantity NUMERIC NOT NULL,
    PRIMARY KEY (OrderNo, ItemNo, FSSAI)
);

ALTER TABLE CUSTOMERS ADD CONSTRAINT FK_CUser FOREIGN KEY (Cust_Uname) REFERENCES USERS (Uname);
ALTER TABLE RESTAURANTS ADD CONSTRAINT FK_RUser FOREIGN KEY (Rest_Uname) REFERENCES USERS (Uname);
ALTER TABLE DELIVERY_PERSONS ADD CONSTRAINT FK_DUser FOREIGN KEY (Del_Uname) REFERENCES USERS (Uname);
ALTER TABLE RESTAURANT_PHONE ADD CONSTRAINT FK_RPhone FOREIGN KEY (FSSAI) REFERENCES RESTAURANTS (FSSAI);
ALTER TABLE FOOD_ITEMS ADD CONSTRAINT FK_Rest_Food FOREIGN KEY (FSSAI) REFERENCES RESTAURANTS (FSSAI);
ALTER TABLE ORDERS ADD CONSTRAINT FK_COrder FOREIGN KEY (Cust_Uname) REFERENCES CUSTOMERS (Cust_Uname);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ROrder FOREIGN KEY (FSSAI) REFERENCES RESTAURANTS (FSSAI);
ALTER TABLE ORDERS ADD CONSTRAINT FK_DOrder FOREIGN KEY (Del_Uname) REFERENCES DELIVERY_PERSONS (Del_Uname);
ALTER TABLE ORDER_CONTENT ADD CONSTRAINT FK_OrderNo FOREIGN KEY (OrderNo)	REFERENCES ORDERS (OrderNo);
ALTER TABLE ORDER_CONTENT ADD CONSTRAINT FK_FoodItem FOREIGN KEY (ItemNo, FSSAI) REFERENCES FOOD_ITEMS (ItemNo, FSSAI);

CREATE OR REPLACE FUNCTION IS_VALID_ITEM (OrderNo INTEGER, FSSAI NUMERIC(14))
RETURNS BOOLEAN
LANGUAGE PLPGSQL AS
$$
BEGIN
	RETURN ($2 = (SELECT FSSAI FROM ORDERS O WHERE O.OrderNo = $1));
END
$$;

ALTER TABLE ORDER_CONTENT ADD CONSTRAINT SameRest CHECK (IS_VALID_ITEM(OrderNo, FSSAI));

CREATE TABLE USER_SESSIONS (
	sid VARCHAR NOT NULL COLLATE "default",
	sess JSON NOT NULL,
	expire TIMESTAMP(6) NOT NULL
) WITH (OIDS=FALSE);
ALTER TABLE USER_SESSIONS ADD CONSTRAINT session_pkey PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX "IDX_session_expire" ON USER_SESSIONS (expire);